// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNxvT3Um_puZlxN-qI3MXZd3Ey-Nnpz-0',
    appId: '1:840749208595:web:5bc14623a2b55eb1601be6',
    messagingSenderId: '840749208595',
    projectId: 'my-event-match',
    authDomain: 'my-event-match.firebaseapp.com',
    storageBucket: 'my-event-match.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDur3llkrRPBT2dVSQwvXsssQhDOyvP_G0',
    appId: '1:840749208595:android:e2dd0b66e619ac41601be6',
    messagingSenderId: '840749208595',
    projectId: 'my-event-match',
    storageBucket: 'my-event-match.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP9PM2DHPLg_hpu6l4RZEZOzSZ8XTeB94',
    appId: '1:840749208595:ios:8e4ea9e85ca3aeda601be6',
    messagingSenderId: '840749208595',
    projectId: 'my-event-match',
    storageBucket: 'my-event-match.firebasestorage.app',
    iosBundleId: 'com.example.newEventmatch',
  );
}
